// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD2LdqJgY1Xdo_epfMBdb3DaZKNmnpctI',
    appId: '1:1093406630735:web:3e03751b54cfda2c229b3a',
    messagingSenderId: '1093406630735',
    projectId: 'flutter-test-sss',
    authDomain: 'flutter-test-sss.firebaseapp.com',
    storageBucket: 'flutter-test-sss.firebasestorage.app',
    measurementId: 'G-QJZVY49ZYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy3uRN6HW0i1UB6zEHhjucrt5koibj9mQ',
    appId: '1:1093406630735:android:a01692d52f00fcba229b3a',
    messagingSenderId: '1093406630735',
    projectId: 'flutter-test-sss',
    storageBucket: 'flutter-test-sss.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2zj0L4iRai0VBlYbPsJjUqj_VLSiugL4',
    appId: '1:1093406630735:ios:5081d0b7d3b0b9d7229b3a',
    messagingSenderId: '1093406630735',
    projectId: 'flutter-test-sss',
    storageBucket: 'flutter-test-sss.firebasestorage.app',
    iosBundleId: 'com.sss.main',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2zj0L4iRai0VBlYbPsJjUqj_VLSiugL4',
    appId: '1:1093406630735:ios:5081d0b7d3b0b9d7229b3a',
    messagingSenderId: '1093406630735',
    projectId: 'flutter-test-sss',
    storageBucket: 'flutter-test-sss.firebasestorage.app',
    iosBundleId: 'com.sss.main',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD2LdqJgY1Xdo_epfMBdb3DaZKNmnpctI',
    appId: '1:1093406630735:web:e868219d5b59a050229b3a',
    messagingSenderId: '1093406630735',
    projectId: 'flutter-test-sss',
    authDomain: 'flutter-test-sss.firebaseapp.com',
    storageBucket: 'flutter-test-sss.firebasestorage.app',
    measurementId: 'G-DQC6WXPEQ7',
  );
}
